sudo: required

language: c

env:
  global:
    - OPENSSL_INSTALL_DIR="${HOME}/opt"

matrix:
  include:
    - env: OPENSSL_VERSION="1.0.2o"
      os: linux
      compiler: gcc
    - env: OPENSSL_VERSION="1.1.0f"
      os: linux
      compiler: gcc
    - env: OPENSSL_VERSION="1.0.2o"
      os: linux
      compiler: clang
    - env: OPENSSL_VERSION="1.1.0f"
      os: linux
      compiler: clang
    - env: DESCRIPTION="check debian package version"
      os: linux
      before_install:
        - true
      script:
        - .ci/check-debian-package-version.sh
    - os: osx
      compiler: clang
      before_install:
        - brew update && brew upgrade openssl
      script:
        - ./configure
        - make -C tmp
        - otool -L bin/vpnserver/vpnserver

addons:
  apt:
    packages: [ debhelper ]

cache:
  directories:
  - download-cache
  - ${HOME}/opt

before_install:
  - bash .ci/build-openssl.sh > build-deps.log 2>&1 || (cat build-deps.log && exit 1)

script:
  - export OPENSSL_ROOT_DIR=${OPENSSL_INSTALL_DIR}
  - export LD_LIBRARY_PATH="${HOME}/opt/lib:${LD_LIBRARY_PATH:-}"
  - export CFLAGS="-I${HOME}/opt/include"
  - export LDFLAGS="-L${HOME}/opt/lib"
  - ./configure
  - make -C tmp
  - ldd bin/vpnserver/vpnserver
  - dh build-arch
